version: '3.8'
services:

  ml-app:
    build: .
    container_name: ntpd-ml-container
    ports:
      - "8080:8080"
    networks:
      - ml-network
    depends_on:
      - redis-db

  redis-db:
    image: "redis:alpine"
    container_name: redis-cache
    ports:
      - "6379:6379" #do bazy danych redis
    networks:
      - ml-network

networks:
  ml-network:
    driver: bridge